version: '3'

services:

  glass-db:
    image: postgres
    env_file:
      - ".env"
    volumes:
      - mydb:/var/lib/postgresql/data
    networks:
      research-network:
        ipv4_address: 172.19.0.15

  glass:
    build: .
    ports:
      - "8080:8080"
    networks:
      research-network:
        ipv4_address: 172.19.0.10


networks:
  research-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.19.0.0/16

volumes:
  mydb:
