openapi: 3.0.0

info:
  title: Glass API
  version: 1.0.0

paths:

  /api/v1/hello:
    get:
      summary: Returns a hello message
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
